#%RAML 1.0 NamedExample
value:
  trackingNumber: "QQ697165015BR"
  trackingUrl: "https://www.linkcorreios.com.br/?id=QQ697165015BR"
  courier: "CORREIOS SEDEX HOJE"
  dispachedDate: "2024-07-15T13:16:13.4617653+00:00"