#%RAML 1.0 NamedExample

value:
  list:
    - orderId: "PCD-1445530960836-01"
      creationDate: "2024-07-08T16:33:50.0000000+00:00"
      clientName: "Marciano Venter"
      items: null
      totalValue: 8394.0
      paymentNames: ""
      status: "ready-for-handling"
      statusDescription: "Pronto para o manuseio"
      marketPlaceOrderId: "1445530960836-01"
      sequence: "500006"
      salesChannel: "13"
      affiliateId: "PCD"
      origin: "Fulfillment"
      workflowInErrorState: false
      workflowInRetry: false
      lastMessageUnread: null
      ShippingEstimatedDate: "2024-07-11T16:33:55.0000000+00:00"
      ShippingEstimatedDateMax: "2024-07-11T16:33:55.0000000+00:00"
      ShippingEstimatedDateMin: "2024-07-11T16:33:55.0000000+00:00"
      orderIsComplete: true
      listId: null
      listType: null
      authorizedDate: "2024-07-08T16:33:58.0000000+00:00"
      callCenterOperatorName: null
      totalItems: 1
      currencyCode: "BRL"
      hostname: "piccadillyiguatemi"
      invoiceOutput: null
      invoiceInput: null
      lastChange: "2024-07-08T16:33:58.0000000+00:00"
      isAllDelivered: false
      isAnyDelivered: false
      giftCardProviders: null
      orderFormId: null
      paymentApprovedDate: null
      readyForHandlingDate: "2024-07-08T17:04:01.0000000+00:00"
      deliveryDates: null
  facets: []
  paging:
      total: 80
      pages: 6
      currentPage: 1
      perPage: 15
  stats:
    stats:
      totalValue:
        Count: 80
        Max: 0.0
        Mean: 0.0
        Min: 0.0
        Missing: 0
        StdDev: 0.0
        Sum: 0.0
        SumOfSquares: 0.0
        Facets: {}
      totalItems:
        Count: 80
        Max: 0.0
        Mean: 0.0
        Min: 0.0
        Missing: 0
        StdDev: 0.0
        Sum: 0.0
        SumOfSquares: 0.0
        Facets: {}
  reportRecordsLimit: 50000