#%RAML 1.0 NamedExample

value:
  type: "Output"
  issuanceDate: "2019-01-302019-01-31T18:25:43-05:00"
  invoiceNumber: 1234
  invoiceValue: 85.90
  invoiceKey: null
  invoiceUrl: null
  courier: null
  trackingNumber: null
  trackingUrl: null
  dispatchedDate: "2019-01-31T18:25:43-05:00"
  items: 
    - id: "1234"
      price: 10000
      quantity: 1