#%RAML 1.0 DataType
displayName: Invoice
description: Defines the Invoice data type

type: object
properties:
  trackingNumber: string
  trackingUrl: string
  courier: string
  dispachedDate: string | nil
  