#%RAML 1.0 DataType

type: object
properties:
  list:
    type: array
    items:
      type: object
      properties:
        orderId: string
        creationDate: string
        clientName: string
        items: string | nil
        totalValue: number
        paymentNames: string | nil
        status?: string
        statusDescription: string
        marketPlaceOrderId: string
        sequence: string
        salesChannel: string
        affiliateId: string
        origin: string
        workflowInErrorState: boolean
        workflowInRetry: boolean
        lastMessageUnread: string | nil
        ShippingEstimatedDate: string
        ShippingEstimatedDateMax: string
        ShippingEstimatedDateMin: string
        orderIsComplete: boolean
        listId: string | nil
        listType: string | nil
        authorizedDate: string
        callCenterOperatorName: string | nil
        totalItems: number
        currencyCode: string
        hostname: string
        invoiceOutput: string | nil
        invoiceInput: string | nil
        lastChange: string
        isAllDelivered: boolean
        isAnyDelivered: boolean
        giftCardProviders: string | nil
        orderFormId: string | nil
        paymentApprovedDate: string | nil
        readyForHandlingDate: string
        deliveryDates: string | nil
  facets: array
  paging: 
    type: object
    properties:
      total: number
      pages: number
      currentPage: number
      perPage: number
  stats: 
    type: object
    properties:
      stats: 
        type: object
        properties:
          totalValue: 
            type: object
            properties:
              Count: number
              Max: number
              Mean: number
              Min: number
              Missing: number
              StdDev: number
              Sum: number
              SumOfSquares: number
              Facets: object
          totalItems:
            type: object
            properties:
              Count: number
              Max: number
              Mean: number
              Min: number
              Missing: number
              StdDev: number
              Sum: number
              SumOfSquares: number
              Facets: object
  reportRecordsLimit: number